// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUBvWgMkao0MJBrxAyde7Pt6q8QJNFxII',
    appId: '1:271103173460:web:b1472dd453caa61318dec1',
    messagingSenderId: '271103173460',
    projectId: 'asynconf-312ff',
    authDomain: 'asynconf-312ff.firebaseapp.com',
    storageBucket: 'asynconf-312ff.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_Zn_0NQoQoq0M_7oPuVcxxx2JFzta7NQ',
    appId: '1:271103173460:android:09839dbe7533f94018dec1',
    messagingSenderId: '271103173460',
    projectId: 'asynconf-312ff',
    storageBucket: 'asynconf-312ff.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDseQ6msfQPpWIhcltBUQ1AYNB5B5dbm5M',
    appId: '1:271103173460:ios:f913a3a712e5b9b518dec1',
    messagingSenderId: '271103173460',
    projectId: 'asynconf-312ff',
    storageBucket: 'asynconf-312ff.firebasestorage.app',
    iosBundleId: 'com.example.asynconf',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDseQ6msfQPpWIhcltBUQ1AYNB5B5dbm5M',
    appId: '1:271103173460:ios:f913a3a712e5b9b518dec1',
    messagingSenderId: '271103173460',
    projectId: 'asynconf-312ff',
    storageBucket: 'asynconf-312ff.firebasestorage.app',
    iosBundleId: 'com.example.asynconf',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUBvWgMkao0MJBrxAyde7Pt6q8QJNFxII',
    appId: '1:271103173460:web:83b1d33b99a300e318dec1',
    messagingSenderId: '271103173460',
    projectId: 'asynconf-312ff',
    authDomain: 'asynconf-312ff.firebaseapp.com',
    storageBucket: 'asynconf-312ff.firebasestorage.app',
  );
}
